First iteration
desepticon55/gofemart pull request #1
Opened 2024-08-10 14:39 UTC by desepticon55

0. Added POST /api/user/register endpoint
1. Added POST /api/user/login endpoint
2. Added POST /api/user/orders endpoint
2. Added GET /api/user/orders endpoint

2024-08-13 12:48 UTC, tmvrus requested changes
А где тесты?

2024-08-13 22:15 UTC, desepticon55 commented
> А где тесты?

Добавил

2024-08-13 22:15 UTC, desepticon55 commented
> А где тесты?

Добавил

2024-08-15 12:51 UTC, tmvrus requested changes
Работа интересная, с тестами по прежнему не все хорошо:
```
go test ./... | grep FAIL
--- FAIL: TestOrderService_UploadOrder (0.01s)
    --- FAIL: TestOrderService_UploadOrder/should_create_order (0.00s)
	1: FAIL:  (common.Order={12345678903 2024-08-15 14:55:24.535521 +0300 MSK m=+0.011725584 2024-08-15 14:55:24.535522 +0300 MSK m=+0.011727168 NEW testUser 0 939914069 85 0}) != (common.Order={12345678903 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 NEW testUser 0 939914069 85 0}) [recovered]
	1: FAIL:  (common.Order={12345678903 2024-08-15 14:55:24.535521 +0300 MSK m=+0.011725584 2024-08-15 14:55:24.535522 +0300 MSK m=+0.011727168 NEW testUser 0 939914069 85 0}) != (common.Order={12345678903 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 NEW testUser 0 939914069 85 0})
FAIL	github.com/desepticon55/gofemart/internal/service/order	0.415s
--- FAIL: TestWorker_ProcessOrders (6.80s)
    --- FAIL: TestWorker_ProcessOrders/should_successfully_processed_order_status_if_response_status_is_200 (1.14s)
        service_test.go:66: FAIL:	ChangeOrderStatus(*context.timerCtx,common.Order,string,float64)
        service_test.go:66: FAIL: 2 out of 3 expectation(s) were met.
    --- FAIL: TestWorker_ProcessOrders/should_successfully_process_order_status_if_response_status_is_200_after_429 (5.61s)
        service_test.go:108: FAIL:	ChangeOrderStatus(*context.timerCtx,common.Order,string,float64)
        service_test.go:108: FAIL: 2 out of 3 expectation(s) were met.
FAIL
FAIL	github.com/desepticon55/gofemart/internal/service/orderworker	7.768s
FAIL
```

2024-08-15 12:51 UTC, tmvrus commented on cmd/gophermart/main.go
> +		panic(err)
тут вполне можно было использовать log.Fatal

2024-08-15 12:51 UTC, tmvrus commented on cmd/gophermart/main.go
> +	"github.com/desepticon55/gofemart/internal/common"
`common ` примерно такое же неудачное наименование для пакета как и `utils`
никакой информации о том, что там может лежать

2024-08-15 12:51 UTC, tmvrus commented on internal/service/orderworker/service.go
> +			w.logger.Error("Error during fetch orders to process", zap.Error(err))
а нужно итерироваться по orders если была ошибка?

2024-08-15 12:51 UTC, tmvrus commented on internal/service/orderworker/service.go
> +				w.logger.Error("Error during wait rate limiter", zap.Error(err))
Тут тоже не ясно, была ошибка, ничего кроме логирования с ней не произошло. Разве не должна она влиять на логику работы приложения?

2024-08-15 12:51 UTC, tmvrus commented on cmd/gophermart/main.go
> +		}(worker)
а почему просто не сделать `go w.ProcessOrders(context.Background(), config.AccrualSystemAddress)` ?

2024-08-15 12:51 UTC, tmvrus commented on internal/api/auth/handler.go
> +		if user.Username == "" || user.Password == "" {
вот этот кусок валидации встречается в двух местах - хендлере и сервисе, хорошо бы определиться какой слой отвечает за валидацию

2024-08-15 12:51 UTC, tmvrus commented on internal/common/model.go
> +type Order struct {
основная бизнес сущность лежит в пакете common, довольно странно

2024-08-15 12:51 UTC, tmvrus commented on internal/common/utils.go
> +			_ = tx.Rollback(ctx)
ну надо хотя бы логировать, а то никогда н узнаем почему ролбек не сработал

2024-08-15 12:51 UTC, tmvrus commented on internal/storage/balanceRepository.go
> +		result, err := tx.Exec(ctx, query, balance.Balance-sum, balance.Version+1, balance.Username, balance.Version)
Что бы не делать такой фокус с версией, достаточно добавить в условие, что результрующий баланс не будет меньше нуля. либо убрать эту проверку на уровень бд, сделав check constraint.

Твой вариант хороший, но сложный и зависит от уровня изоляции.

2024-08-15 12:51 UTC, tmvrus commented on internal/storage/orderRepository.go
> +		query := `insert into gofemart.order(order_number, username, create_date, last_modify_date, status, accrual, key_hash, key_hash_module, opt_lock)
а какой смысл запускать один запрос в транзакции?

2024-08-15 12:51 UTC, tmvrus commented on internal/service/order/service.go
> +			KeyHashModule:  keyHash % int64(common.Module),
мудрено, проще же было сделать один воркер который выгребает все заказы и раздает их по каналу воркерам для проверки, если хочется не сколько выгребателей то можно считать остаток от деления номера ордера. всяко проще чем с диапазонами.

2024-08-15 12:51 UTC, tmvrus commented on internal/service/orderworker/service.go
> +
странно что все остальные статусы не обрабатываются, хотя бы для логирования

2024-08-15 12:51 UTC, tmvrus commented on internal/common/utils.go
> +func Transactional(ctx context.Context, pool *pgxpool.Pool, fn TransactionFunc) (err error) {
зачем хранить тут то, что нужно только в репозитории?

2024-08-16 08:40 UTC, desepticon55 commented on cmd/gophermart/main.go
> +		}(worker)
Ты прав, переделал

2024-08-16 08:41 UTC, desepticon55 commented on cmd/gophermart/main.go
> +		panic(err)
Поправил

2024-08-16 08:43 UTC, desepticon55 commented
> Работа интересная, с тестами по прежнему не все хорошо:
> 
> ```
> go test ./... | grep FAIL
> --- FAIL: TestOrderService_UploadOrder (0.01s)
>     --- FAIL: TestOrderService_UploadOrder/should_create_order (0.00s)
> 	1: FAIL:  (common.Order={12345678903 2024-08-15 14:55:24.535521 +0300 MSK m=+0.011725584 2024-08-15 14:55:24.535522 +0300 MSK m=+0.011727168 NEW testUser 0 939914069 85 0}) != (common.Order={12345678903 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 NEW testUser 0 939914069 85 0}) [recovered]
> 	1: FAIL:  (common.Order={12345678903 2024-08-15 14:55:24.535521 +0300 MSK m=+0.011725584 2024-08-15 14:55:24.535522 +0300 MSK m=+0.011727168 NEW testUser 0 939914069 85 0}) != (common.Order={12345678903 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 2024-08-15 14:55:24.535439 +0300 MSK m=+0.011643793 NEW testUser 0 939914069 85 0})
> FAIL	github.com/desepticon55/gofemart/internal/service/order	0.415s
> --- FAIL: TestWorker_ProcessOrders (6.80s)
>     --- FAIL: TestWorker_ProcessOrders/should_successfully_processed_order_status_if_response_status_is_200 (1.14s)
>         service_test.go:66: FAIL:	ChangeOrderStatus(*context.timerCtx,common.Order,string,float64)
>         service_test.go:66: FAIL: 2 out of 3 expectation(s) were met.
>     --- FAIL: TestWorker_ProcessOrders/should_successfully_process_order_status_if_response_status_is_200_after_429 (5.61s)
>         service_test.go:108: FAIL:	ChangeOrderStatus(*context.timerCtx,common.Order,string,float64)
>         service_test.go:108: FAIL: 2 out of 3 expectation(s) were met.
> FAIL
> FAIL	github.com/desepticon55/gofemart/internal/service/orderworker	7.768s
> FAIL
> ```

Странно, у меня локально все проходит. Немного переписал проверку на моках.

2024-08-16 08:59 UTC, desepticon55 commented on cmd/gophermart/main.go
> +	"github.com/desepticon55/gofemart/internal/common"
поправил

2024-08-16 09:04 UTC, desepticon55 commented on internal/service/orderworker/service.go
> +			w.logger.Error("Error during fetch orders to process", zap.Error(err))
Согласен, упустил этот момент. Добавил паузу перед новой попыткой

2024-08-16 09:04 UTC, desepticon55 commented on internal/service/orderworker/service.go
> +				w.logger.Error("Error during wait rate limiter", zap.Error(err))
Согласен, упустил этот момент. Добавил паузу перед новой попыткой

2024-08-16 09:10 UTC, desepticon55 commented on internal/storage/balanceRepository.go
> +		result, err := tx.Exec(ctx, query, balance.Balance-sum, balance.Version+1, balance.Username, balance.Version)
так в целом все приложение проектируется под конкретный уровень изоляции, это, как мне кажется, основа основ при проектировании какого-либо механизма. В данном случае я явно заложил упор на то, что уровень изоляции будет Read commited, отсюда и версия. В части констрейнта в БД не очень нравится идея, т.к. эта логика будет изолирована в базе и надо будет о ней помнить. А так, я в сервисном слое получил баланс, проверил его и послал запрос на изменение в репозиторий. Если была параллельная транзакция, то изменение будет только одно. Если вопрос принципиальный, то могу переписать

2024-08-16 09:13 UTC, desepticon55 commented on internal/storage/orderRepository.go
> +		query := `insert into gofemart.order(order_number, username, create_date, last_modify_date, status, accrual, key_hash, key_hash_module, opt_lock)
Абсолютно никакого :) убрал

2024-08-16 09:26 UTC, desepticon55 commented on internal/service/order/service.go
> +			KeyHashModule:  keyHash % int64(common.Module),
Проще, но я тут думал про то, что сейчас, возможно, у нас будет 1 инстанс приложения и тогда можно внутри него горутинами решить вопрос конкурентного разбора заказов. Но такой алгоритм с диапазонами я заложил на будущее, когда инстансов будет N. Тут я бы развил этот механизм сл. образом:
1. Делаем группу фоновых операций, некая таблица job
2. При старте сервиса, в отдельной горутинке формируем интервалы и на каждый интервал создаем задачу, сохраняем ее в Job и паблишим в кафку сами себе событие о том, что задачу с таким-то идентификатором можно запустить
3. Т.к. у нас появилась кафка - это бесплатная балансировка нагрузки между инстансами, какой-то инстанс поймает событие, запустит задачу и начнет выгребать заказы в заданном интервале.
4. Если произошла ошибка, то задача переводится в FAILED с фиксацией причины ошибки (для дальнейшего разбора)
5. Если ошибки нет, обрабатываем заказы, в конце встаем в паузу на некоторе время. Если данных для обработки нет, тоже встаем в паузу на некоторое время.
Таким образом, мы получаем распределенный механизм разгребания очереди заказов (удобно, если у нас окажется много пользователей и 1 инстанс не будет справляться, в реальной боевой системе чаще всего более 1 инстанса приложения)

Теперь по части ошибки, можно сделать еще один single node фоновый процесс, который будет отслеживать задания в статусе FAILED (некий супервизов). Находит такие задания и снова посылает запрос на формирование новой задачи в таком же интервале. 

Таким образом мы получаем группу задач, которая умеет скейлиться на несколько инстансов и, в случае, ошибки, может восстановиться.

Механизма сложная, но хорошая. Т.к. в рамках данного проекта не планировалось использовать kafka, я просто сделал упрощенную штуку, но с заделом на будущее.

2024-08-16 09:29 UTC, desepticon55 commented on internal/service/orderworker/service.go
> +
Добавил логов :)

2024-08-16 09:51 UTC, desepticon55 commented on internal/common/utils.go
> +func Transactional(ctx context.Context, pool *pgxpool.Pool, fn TransactionFunc) (err error) {
Согласен, растащил все эти вспомогательные функции по областям применения

2024-08-16 09:54 UTC, desepticon55 commented on internal/common/utils.go
> +			_ = tx.Rollback(ctx)
Поправил

2024-08-16 09:55 UTC, desepticon55 commented on internal/common/model.go
> +type Order struct {
Согласен, поправил, теперь модельки лежат в пакете model

2024-08-16 09:58 UTC, desepticon55 commented on internal/api/auth/handler.go
> +		if user.Username == "" || user.Password == "" {
Унес в сервисный слой

2024-08-16 14:54 UTC, tmvrus approved these changes
Работа безусловно хорошая, но на мой взгляд, ты сосредоточился на черезмерной оптимизации и усложнении, а лучше было сосредоточиться на тестах, которые все равно падают, видимо потому что у меня ничего не запущено по нужному адресу
```bash
--- FAIL: TestWorker_ProcessOrders (6.01s)
    logger.go:146: 2024-08-16T17:44:47.897+0300	DEBUG	Accrual address prepared	{"address": "http://127.0.0.1:61230/api/orders/12345"}
    logger.go:146: 2024-08-16T17:44:47.911+0300	ERROR	Error during process order	{"error": "error during send event: Get \"http://127.0.0.1:61230/api/orders/12345\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
    --- FAIL: TestWorker_ProcessOrders/should_successfully_processed_order_status_if_response_status_is_200 (1.01s)
```
Еще можно было подумать о том, как корректно остановить воркеры, и прогнать код через линтер не мешало бы.

2024-08-24 19:10 UTC, merged